# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleadore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('edad', models.IntegerField()),
                ('trabajo', models.CharField(max_length=120)),
                ('correo', models.CharField(max_length=120)),
                ('imagen', models.ImageField(upload_to='imagenesPerfilEmpleadores')),
            ],
        ),
        migrations.CreateModel(
            name='Especializacione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especializacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Especializacion', to='BackendWeb.Especializacione')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=120)),
                ('numero', models.IntegerField()),
                ('colonia', models.CharField(max_length=200)),
                ('delegacionMunicipio', models.CharField(max_length=120)),
                ('tipoLugar', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='trabajo',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ubicacion', to='BackendWeb.Ubicacione'),
        ),
    ]
